"""add column estimated_monthly

Revision ID: 19653ede5bac
Revises: b25b7e1685c8
Create Date: 2025-11-29 05:01:11.702702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19653ede5bac'
down_revision: Union[str, Sequence[str], None] = 'b25b7e1685c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('estimated_monthly', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'estimated_monthly')
    # ### end Alembic commands ###
