"""add column estimated_weekly

Revision ID: 8ba3fd17f042
Revises: 19653ede5bac
Create Date: 2025-11-29 05:06:27.259602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba3fd17f042'
down_revision: Union[str, Sequence[str], None] = '19653ede5bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('estimated_weekly', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'estimated_weekly')
    # ### end Alembic commands ###
