"""updated the user table

Revision ID: 97e1f4c20582
Revises: 8ba3fd17f042
Create Date: 2025-11-29 05:12:16.010865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e1f4c20582'
down_revision: Union[str, Sequence[str], None] = '8ba3fd17f042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('essentials_pct', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('bills_pct', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('savings_pct', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('fun_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fun_pct')
    op.drop_column('users', 'savings_pct')
    op.drop_column('users', 'bills_pct')
    op.drop_column('users', 'essentials_pct')
    # ### end Alembic commands ###
